//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectName.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> StockStatusID { get; set; }
        public Nullable<int> UnitsInStock { get; set; }
        public decimal Price { get; set; }
        public bool IsMensApperal { get; set; }
        public bool IsFemaleApperal { get; set; }
        public bool OtherApperal { get; set; }
        public string ProductImage { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual StockStatu StockStatu { get; set; }
    }
}
